# Generated by Django 2.2.2 on 2019-06-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='摄像头名称', max_length=128, verbose_name='名称')),
                ('useType', models.IntegerField(choices=[(0, '未知'), (1, '人脸检测'), (2, '安全帽检测'), (3, '安全带检测'), (4, '跨越围栏动作检测')], default=0, verbose_name='用途')),
                ('ip', models.CharField(blank=True, help_text='摄像头的ip地址', max_length=100, null=True, verbose_name='ip地址')),
                ('address', models.CharField(max_length=50, verbose_name='安装地点')),
                ('enable', models.BooleanField(default=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '摄像头',
                'verbose_name_plural': '摄像头管理',
            },
        ),
    ]
