# Generated by Django 2.2.2 on 2019-08-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='event.png', height_field='photo_height', upload_to='events/%Y-%m-%d/', verbose_name='照片', width_field='photo_width'),
        ),
    ]
