# Generated by Django 2.2.2 on 2019-06-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='enable',
        ),
    ]
