# Generated by Django 2.2.2 on 2019-08-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20190806_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='birthday',
            field=models.DateField(default='1900-01-01', verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, '未知'), (1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', height_field='photo_height', null=True, upload_to='photos/%Y-%m-%d/', verbose_name='照片', width_field='photo_width'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='photo_height',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='高度'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='photo_width',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='宽度'),
        ),
    ]
