# Generated by Django 2.2.2 on 2019-06-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_department_employe_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='photo',
            field=models.ImageField(default='default.png', height_field='url_height', upload_to='photos', width_field='url_width'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
