# Generated by Django 2.2.2 on 2019-08-04 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_auto_20190804_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='online_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='在线时间'),
        ),
        migrations.AddField(
            model_name='camera',
            name='password',
            field=models.CharField(db_index=True, default='', help_text='摄像头连接密码', max_length=128, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='camera',
            name='state',
            field=models.IntegerField(choices=[(0, '在线'), (1, '离线')], default=0, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='camera',
            name='username',
            field=models.CharField(db_index=True, default='', help_text='摄像头连接用户名', max_length=128, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='default.png', height_field='photo_height', upload_to='photos', width_field='photo_width'),
        ),
        migrations.AddField(
            model_name='event',
            name='photo_height',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='photo_width',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
