# Generated by Django 2.2.2 on 2019-08-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_auto_20190806_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='employe',
        ),
    ]
