# Generated by Django 2.2.2 on 2019-06-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_auto_20190605_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='photo_height',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='employe',
            name='photo_width',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employe',
            name='photo',
            field=models.ImageField(default='default.png', height_field='photo_height', upload_to='photos', width_field='photo_width'),
        ),
    ]
