# Generated by Django 2.2.2 on 2019-08-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_auto_20190804_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='state',
        ),
        migrations.AlterField(
            model_name='employe',
            name='photo',
            field=models.ImageField(default='default.png', height_field='photo_height', upload_to='photos', verbose_name='照片', width_field='photo_width'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='photo_height',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='高度'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='photo_width',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='宽度'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='default.png', height_field='photo_height', upload_to='photos', verbose_name='照片', width_field='photo_width'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo_height',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='高度'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo_width',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='宽度'),
        ),
    ]
