# Generated by Django 2.2.2 on 2019-08-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_remove_event_employe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': '作业场所', 'verbose_name_plural': '作业场所'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '违章记录', 'verbose_name_plural': '违章记录'},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': '违章行为', 'verbose_name_plural': '违章行为'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': '作业单位', 'verbose_name_plural': '作业单位'},
        ),
        migrations.RemoveField(
            model_name='camera',
            name='address',
        ),
        migrations.AddField(
            model_name='event',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.Position', verbose_name='作业单位'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(db_index=True, help_text='作业场所应该唯一', max_length=128, unique=True, verbose_name='作业场所'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.EventType', verbose_name='违章记录'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(db_index=True, help_text='违章行为名称，如跨越围栏等', max_length=128, unique=True, verbose_name='违章行为'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(db_index=True, help_text='一个区域包含多个位置', max_length=128, verbose_name='作业单位'),
        ),
    ]
