# Generated by Django 2.2.2 on 2019-08-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_auto_20190804_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(db_index=True, help_text='一个区域包含多个位置', max_length=128, verbose_name='安装位置'),
        ),
    ]
